language: cpp

script: cmake .

compiler:
  - clang
  - gcc-8

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main universe"
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y g++-8 libtinyxml2-dev libegl1-mesa-dev libgles2-mesa-dev libsdl2-dev libsdl2-mixer-dev libsdl2-image-dev libglm-dev cmake cxxtest
  - export CXX=g++-8
  - export CC=gcc-8
  # - sudo apt-add-repository -y ppa:zoogie/sdl2-snapshots
  # - sudo add-apt-repository --yes ppa:kubuntu-ppa/backports

script:
  - cmake .
  - make

os: linux

notifications:
  email: false
  irc:
    channels:
      - "irc.smoothirc.net#zeldaool"
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"

